name: flutter_web_example
version: 1.0.0+1
publish_to: none
description: Flutter Web Example.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^14.1.4
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  uuid: ^4.4.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.10
  json_serializable: ^6.8.0

flutter: 
  uses-material-design: true

