name: flutter_web_example
version: 1.0.0+1
publish_to: none
description: Flutter Web Example.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter: 
    sdk: flutter
  go_router: ^14.1.0
  uuid: ^4.4.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

